Fix "ImportError: No module named backports"
AppVeyor doesn't have backports installed in the 2.7 test so xz decompression fails.

Should fix the following errors:

ERROR: Test reading xz-compressed tables from URL: compression="infer", engine="python"

ERROR: Test reading xz-compressed tables from URL: compression="infer", engine="c"